name: Java CI with Maven
on:
  push:
    branches: [ "main" ]
env:
  APP_NAME: devops-java-demo
  MAVEN_ARGS: "-B"
jobs:
 compile:
    name: Compile Project 
    runs-on: ubuntu-latest

    env:
      STAGE_NAME: compile-stage

    steps:
    - uses: actions/checkout@v4 
    
    - name: Show Default + Manual ENV
      run: |
       echo "App Name: $APP_NAME"
       echo "Stage: $STAGE_NAME"
       echo "Branch: $GITHUB_REF"
       echo "Commit: $GITHUB_SHA"

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Compile with Maven
      run: mvn $MAVEN_ARGS compile --file pom.xml
      
 test:
    name: Execute unit test project
    runs-on: ubuntu-latest
    needs: compile

    env:
     STAGE_NAME: test-stage
      
    steps:
    - uses: actions/checkout@v4

    - name: Print Default ENV
      run: echo "Triggered by $GITHUB_ACTOR on $GITHUB_REF"
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Execute unit tests
      run: mvn $MAVEN_ARGS test
 build:
    name: build project
    runs-on: ubuntu-latest
    needs: test

    env:
      STAGE_NAME: build-stage


    steps:
    - uses: actions/checkout@v4
    
    - name: Custom Step Env Demo
      env:
         BUILD_TYPE: release
        run: echo "Build Type is $BUILD_TYPE"

    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: mvn_build
      run: mvn $MAVEN_ARGS package

    - uses: actions/upload-artifact@v7
      with:
        name: boardgame
        path: target/*.jar
